version: "2"

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    volumes:
      - "/volume2/docker/data/nexus/nexus-data:/nexus-data"
    ports:
      - "8081:8081"
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    networks:
      macvlan_ovs_eth0:
          ipv4_address: 172.16.156.106
          aliases: 
            - Docker-Nexus
    deploy:
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 3072M

networks:
  macvlan_ovs_eth0:
    external: true